#!/bin/bash

#SBATCH --job-name=exp_run
#SBATCH --output=isca%s.out
#SBATCH --error=isca%s.err
#SBATCH --time=03:00:00 # maximum walltime for the job
#SBATCH --nodes=1 # specify number of nodes
#SBATCH --ntasks-per-node=%s # specify number of processors per node
#SBATCH --mail-type=END # send email at job completion
#SBATCH --mail-user=USER@st-andrews.ac.uk # email address

python ~/isca_jobs/record_time.py TIMES_held_suarez_test_%s_processor START

cd ~/isca/exp/test_cases/
python held_suarez/held_suarez_test_case.py

python ~/isca_jobs/record_time.py TIMES_held_suarez_test_%s_processor END
